---
- name: Check if swap file exists
  ansible.builtin.stat:
    path: /swapfile
  register: swap_file_check

- name: Create 2GB swap file
  ansible.builtin.command: dd if=/dev/zero of=/swapfile bs=1M count=2048
  when: not swap_file_check.stat.exists
  changed_when: not swap_file_check.stat.exists
  become: true

- name: Set swap file permissions
  ansible.builtin.file:
    path: /swapfile
    mode: "0600"
    owner: root
    group: root
  become: true

- name: Make swap file
  ansible.builtin.command: mkswap /swapfile
  when: not swap_file_check.stat.exists
  changed_when: not swap_file_check.stat.exists
  become: true

- name: Enable swap file
  ansible.builtin.command: swapon /swapfile
  when: not swap_file_check.stat.exists
  changed_when: not swap_file_check.stat.exists
  become: true

- name: Add swap to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile none swap sw 0 0"
    state: present
  become: true

- name: Set swappiness to 10
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    sysctl_set: true
  become: true

- name: Set cache pressure
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    sysctl_set: true
  become: true
