apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  # These values will be set by CI/CD pipeline
  database-username: {{ .Values.database.username | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  database-name: {{ .Values.database.name | b64enc }}
