# Default values for monitoring
replicaCount:
  prometheus: 1
  grafana: 1

prometheus:
  image:
    repository: prom/prometheus
    tag: "v2.45.0"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 200m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  retention: "7d"
  scrapeInterval: "30s"
  
  service:
    type: ClusterIP
    port: 9090

grafana:
  image:
    repository: grafana/grafana
    tag: "10.0.3"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  service:
    type: ClusterIP
    port: 3000

nodeExporter:
  image:
    repository: prom/node-exporter
    tag: "v1.6.1"
    pullPolicy: IfNotPresent
  
  resources:             
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 25m
      memory: 16Mi

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  
  grafana:
    host: grafana.dock.ink
  prometheus:
    host: prometheus.dock.ink
