# Backend values for prod
# namespace: prod

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 386Mi

database:
  host: database-service
  port: 5432
  name: ""
  username: ""
  password: ""

spring:
  profiles:
    active: prod

ingress:
  enabled: true
  hosts:
    - host: api.dock.ink
      paths:
        - path: /
          pathType: Prefix
