# Database values for prod
namespace: prod

image:
  repository: postgres
  tag: "13-alpine"
  pullPolicy: IfNotPresent
  
replicaCount: 1

resources:
  limits:
    cpu: 300m  # 0.3 CPU
    memory: 256Mi
  requests:
    cpu: 150m  # 50% от limits
    memory: 128Mi  # 50% от limits
    
postgresql:
  database: database
  username: postgres
  password: mypassword1
  
persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"
