# Database values for prod
namespace: prod

image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent
  
replicaCount: 1

resources:
  limits:
    cpu: 300m  # 0.3 CPU
    memory: 256Mi
  requests:
<<<<<<< HEAD
    cpu: 150m  # 50% от limits
    memory: 128Mi  # 50% от limits
    
=======
    cpu: 150m
    memory: 128Mi

>>>>>>> dc60a4b (Update terraform and workflows)
postgresql:
  database: database
  username: postgres
  password: mypassword1
  
persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"
