---
- name: Restart postgres
  community.docker.docker_container:
    name: postgres
    state: started
    restart: true
  become: true

- name: Restart redis
  community.docker.docker_container:
    name: redis
    state: started
    restart: true
  become: true
