---
- name: Deploy application services
  hosts: all
  roles:
    - common
    - swap
  tags:
    - always

- name: Deploy database
  hosts: database_group
  roles:
    - database
  vars_files:
    - group_vars/database/vault.yml
  tags: database

- name: Deploy backend
  hosts: backend_group
  roles:
    - backend
  vars:
    database_private_ip: "{{ hostvars['database_host']['ansible_host'] }}"
  vars_files:
    - group_vars/database/vault.yml
  tags: backend

- name: Deploy frontend
  hosts: frontend_group
  roles:
    - frontend
  tags: frontend

- name: Deploy reverse proxy
  hosts: bastion_group
  roles:
    - reverse-proxy
  vars:
    frontend_private_ip: "{{ hostvars['frontend_host']['ansible_host'] }}"
    backend_private_ip: "{{ hostvars['backend_host']['ansible_host'] }}"
  tags: reverse-proxy

- name: Deploy monitoring
  hosts: monitoring_group
  roles:
    - monitoring
  vars_files:
    - group_vars/database/vault.yml
  tags: monitoring
