# argocd/backend-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/git-ig/k3class
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - ../../environments/prod/backend-values.yaml
      parameters:
        - name: image.tag
          value: "latest"
        - name: namespace
          value: "prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
