apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  # These values will be set by CI/CD pipeline
  postgres-password: {{ .Values.postgresql.password | b64enc }}
  postgres-username: {{ .Values.postgresql.username | b64enc }}
  postgres-database: {{ .Values.postgresql.database | b64enc }}
