apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  grafana-admin-password: {{ .Values.grafana.adminPassword | b64enc }}
