apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: 9090
    name: http
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: 3000
    name: http
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
