---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true

- name: Remove default Nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Create reverse proxy configuration
  ansible.builtin.template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse-proxy
    mode: "0644"
  become: true
  notify: Restart nginx

- name: Enable reverse proxy site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/reverse-proxy
    dest: /etc/nginx/sites-enabled/reverse-proxy
    state: link
  become: true
  notify: Restart nginx

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  become: true
