---
# Ports
backend_port: 8080
frontend_port: 80
database_port: 5432
redis_port: 6379

# Dynamic URL (use PUBLIC IP of reverse proxy)
backend_api_url: "http://{{ hostvars['bastion_host']['ansible_host'] }}/api/"
database_url: "{{ hostvars['database_host']['ansible_host'] }}:{{ database_port }}"
redis_url: "{{ hostvars['database_host']['ansible_host'] }}:{{ redis_port }}"

# env config
app_environment: production
log_level: info

# Monitoring configuration
grafana_admin_password: "{{ vault_grafana_admin_password }}"
ansible_user_uid: 1000
ansible_user_gid: 1000
