name: Deploy Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_run:
    workflows: ["Frontend CI", "Deploy Database"]
    types:
      - completed
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: frontend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-frontend:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Use existing SSH Key and Create tfvars
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.GCP_SSH_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub

          cat > infra/terraform/gcp/terraform.tfvars << EOF
          project_id               = "${{ secrets.GCP_PROJECT_ID }}"
          region                   = "${{ secrets.GCP_REGION }}"
          zone                     = "${{ secrets.GCP_ZONE }}"
          ssh_user                 = "${{ secrets.GCP_SSH_USER }}"
          ssh_public_key_content   = "$SSH_PUBLIC_KEY"
          bucket_name              = "${{ secrets.GCS_BUCKET_NAME }}"
          service_account_email    = "schedule-frontend@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          cloudflare_api_token     = "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          cloudflare_zone_id       = "${{ secrets.CLOUDFLARE_ZONE_ID }}"
          EOF

      - name: Debug Terraform Variables
        run: |
          echo "===  TERRAFORM VARIABLES DEBUG ==="
          echo "Project ID from secret: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Expected SA email: schedule-frontend@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          echo ""
          echo " Generated terraform.tfvars content:"
          cat infra/terraform/gcp/terraform.tfvars
          echo ""
          echo " Checking if service account exists:"
          gcloud iam service-accounts describe schedule-frontend@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com || echo "❌ Service account not found!"
          echo ""
          echo " Checking variable in storage module:"
          grep -n "service_account_email" infra/terraform/gcp/modules/storage/main.tf || echo "❌ Variable not found in storage module!"
          echo "================================="

      - name: Configure Ansible Vault
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: echo "$ANSIBLE_VAULT_PASSWORD" > infra/ansible/.vault_pass

      - name: Create Terraform backend config
        env:
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        working-directory: infra/terraform/gcp
        run: |
          echo "bucket = \"$GCS_BUCKET_NAME\"" > backend.conf
          echo "prefix = \"terraform/state\"" >> backend.conf

      - name: Initialize Terraform
        working-directory: infra/terraform/gcp
        run: terraform init -backend-config=backend.conf

      - name: Terraform Apply
        working-directory: infra/terraform/gcp
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Setup SSH Agent and Config
        env:
          GCP_SSH_USER: ${{ secrets.GCP_SSH_USER }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          cd infra/terraform/gcp
          BASTION_IP=$(terraform output -raw bastion_public_ip)
          cd ../../..

          cat > ~/.ssh/config << EOF
          Host bastion
            HostName $BASTION_IP
            User $GCP_SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ForwardAgent yes

          Host 10.0.*.*
            User $GCP_SSH_USER
            IdentityFile ~/.ssh/id_rsa
            ProxyJump bastion
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF

      - name: Generate Ansible Inventory
        id: terraform_outputs
        working-directory: infra/terraform/gcp
        run: |
          BASTION_IP=$(terraform output -raw bastion_public_ip)
          FRONTEND_IP=$(terraform output -raw frontend_private_ip)
          BACKEND_IP=$(terraform output -raw backend_private_ip)
          DATABASE_IP=$(terraform output -raw database_private_ip)
          MONITORING_IP=$(terraform output -raw monitoring_private_ip)
          SSH_USER="${{ secrets.GCP_SSH_USER }}"

          mkdir -p ../../ansible/inventory

          cat > ../../ansible/inventory/gcp.yml << EOF
          ---
          all:
            vars:
              ansible_user: $SSH_USER
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
            children:
              bastion_group:
                hosts:
                  bastion_host:
                    ansible_host: $BASTION_IP
              private_instances:
                vars:
                  ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q $SSH_USER@$BASTION_IP -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
                children:
                  frontend_group:
                    hosts:
                      frontend_host:
                        ansible_host: $FRONTEND_IP
                  backend_group:
                    hosts:
                      backend_host:
                        ansible_host: $BACKEND_IP
                  database_group:
                    hosts:
                      database_host:
                        ansible_host: $DATABASE_IP
                  monitoring_group:
                    hosts:
                      monitoring_host:
                        ansible_host: $MONITORING_IP
          EOF

          echo "frontend_image=ghcr.io/${{ github.repository }}-frontend:${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT

      - name: Run Frontend Playbook
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-galaxy collection install community.docker

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          ansible-playbook deploy.yml \
            --vault-password-file .vault_pass \
            --extra-vars "frontend_image_url=${{ steps.terraform_outputs.outputs.frontend_image }}" \
            --limit frontend_group \
            -vv
