# Backend values for dev
namespace: dev

image:
  repository: ghcr.io/${{ github.repository }}
  tag: "${{ env.IMAGE_TAG }}"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

database:
  host: database-service
  port: 5432
  name: ${{ secrets.DATABASE_NAME }}
  username: ${{ secrets.DATABASE_USERNAME }}
  password: ${{ secrets.DATABASE_PASSWORD }}

spring:
  profiles:
    active: dev

ingress:
  enabled: true
  hosts:
    - host: dev-api.dock.ink
      paths:
        - path: /api
          pathType: Prefix
