# Database values for dev
namespace: dev

image:
  repository: postgres
  tag: "13-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 125m
    memory: 128Mi

postgresql:
  database: ${{ secrets.DATABASE_NAME }}
  username: ${{ secrets.DATABASE_USERNAME }}
  password: ${{ secrets.DATABASE_PASSWORD }}

persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"
